<?php

namespace Database\Seeders;

use App\Models\Hospital;
use Illuminate\Database\Seeder;

class HospitalDirectorySeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'name' => 'Hopital Sainte Marie Delmas',
                'phone' => '+509-2810-3401',
                'address' => 'Delmas 75, Port-au-Prince',
                'latitude' => 18.5578,
                'longitude' => -72.2956,
                'open_now' => true,
                'opening_hours' => 'Lun-Ven 07:00-19:00; Sam 08:00-15:00; Dim urgence uniquement',
                'closes_at' => '19:00',
                'temporary_closed' => false,
                'emergency_available' => true,
                'services' => 'Urgences, Medecine generale, Pediatrie, Imagerie simple',
                'payment_methods' => 'Cash (HTG/USD), MonCash, NatCash, Carte de debit locale',
                'price_range' => 'medium',
                'average_wait_time' => 35,
                'delivery_available' => false,
                'night_service' => true,
                'license_number' => 'HOS-PAP-1001',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Piece d\'identite recommandee pour l\'enregistrement.',
            ],
            [
                'name' => 'Centre Hospitalier Turgeau',
                'phone' => '+509-2810-3402',
                'address' => 'Turgeau, Port-au-Prince',
                'latitude' => 18.5324,
                'longitude' => -72.3269,
                'open_now' => true,
                'opening_hours' => 'Lun-Sam 06:30-20:00; Dim 08:00-13:00',
                'closes_at' => '20:00',
                'temporary_closed' => false,
                'emergency_available' => true,
                'services' => 'Urgences, Maternite, Laboratoire de base, Consultation specialisee',
                'payment_methods' => 'Cash (HTG/USD), MonCash, Sogebank, Unibank',
                'price_range' => 'medium',
                'average_wait_time' => 45,
                'delivery_available' => false,
                'night_service' => true,
                'license_number' => 'HOS-PAP-1002',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Service urgence ouvert 24h/24.',
            ],
            [
                'name' => 'Hopital Communautaire Carrefour-Feuilles',
                'phone' => '+509-2810-3403',
                'address' => 'Carrefour-Feuilles, Port-au-Prince',
                'latitude' => 18.5254,
                'longitude' => -72.3422,
                'open_now' => true,
                'opening_hours' => 'Lun-Ven 07:00-18:00; Sam 08:00-14:00',
                'closes_at' => '18:00',
                'temporary_closed' => false,
                'emergency_available' => false,
                'services' => 'Medecine familiale, Vaccination, Soins infirmiers, Petite chirurgie',
                'payment_methods' => 'Cash (HTG), MonCash, NatCash',
                'price_range' => 'low',
                'average_wait_time' => 30,
                'delivery_available' => false,
                'night_service' => false,
                'license_number' => 'HOS-PAP-1003',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Consultations pediatriques priorisees le matin.',
            ],
            [
                'name' => 'Clinique Hospitaliere Bois Verna',
                'phone' => '+509-2810-3404',
                'address' => 'Bois Verna, Port-au-Prince',
                'latitude' => 18.5389,
                'longitude' => -72.3331,
                'open_now' => false,
                'opening_hours' => 'Lun-Ven 08:00-17:30; Sam 08:00-12:30',
                'closes_at' => '17:30',
                'temporary_closed' => false,
                'emergency_available' => false,
                'services' => 'Consultation interne, Cardiologie, Ultrasons, Pharmacie interne',
                'payment_methods' => 'Cash (HTG/USD), MonCash, Virement bancaire local',
                'price_range' => 'high',
                'average_wait_time' => 50,
                'delivery_available' => false,
                'night_service' => false,
                'license_number' => 'HOS-PAP-1004',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Rendez-vous recommandes pour specialites.',
            ],
            [
                'name' => 'Hopital Metropolitain de Petion-Ville',
                'phone' => '+509-2810-3405',
                'address' => 'Route de Freres, Petion-Ville',
                'latitude' => 18.5168,
                'longitude' => -72.2861,
                'open_now' => true,
                'opening_hours' => 'Lun-Dim 00:00-23:59 (service continu)',
                'closes_at' => null,
                'temporary_closed' => false,
                'emergency_available' => true,
                'services' => 'Urgences 24h/24, Chirurgie, Radiologie, Hospitalisation',
                'payment_methods' => 'Cash (HTG/USD), MonCash, NatCash, Carte internationale',
                'price_range' => 'high',
                'average_wait_time' => 40,
                'delivery_available' => false,
                'night_service' => true,
                'license_number' => 'HOS-PAP-1005',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Triage rapide pour cas critiques.',
            ],
        ];

        foreach ($rows as $row) {
            Hospital::updateOrCreate(
                ['name' => $row['name']],
                array_merge($row, [
                    'license_verified_at' => null,
                    'license_verified_by_doctor_id' => null,
                    'license_verification_notes' => null,
                    'last_status_updated_at' => now(),
                    'delivery_radius_km' => null,
                ])
            );
        }
    }
}

