<?php

namespace Database\Seeders;

use App\Models\Laboratory;
use Illuminate\Database\Seeder;

class LaboratoryDirectorySeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'name' => 'Laboratoire Central Delmas',
                'phone' => '+509-2811-4101',
                'address' => 'Delmas 33, Port-au-Prince',
                'latitude' => 18.5487,
                'longitude' => -72.3154,
                'open_now' => true,
                'opening_hours' => 'Lun-Sam 06:30-18:00; Dim 07:00-12:00',
                'closes_at' => '18:00',
                'temporary_closed' => false,
                'emergency_available' => false,
                'services' => 'Hemogramme, Glycemie, Bilan lipidique, Analyse d\'urine',
                'payment_methods' => 'Cash (HTG), MonCash, NatCash, Virement local',
                'price_range' => 'medium',
                'average_wait_time' => 20,
                'delivery_available' => true,
                'delivery_radius_km' => 6.0,
                'night_service' => false,
                'license_number' => 'LAB-PAP-2001',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Resultats standards disponibles en 24 heures.',
            ],
            [
                'name' => 'BioAnalyse Turgeau',
                'phone' => '+509-2811-4102',
                'address' => 'Turgeau, Port-au-Prince',
                'latitude' => 18.5334,
                'longitude' => -72.3279,
                'open_now' => true,
                'opening_hours' => 'Lun-Ven 07:00-19:00; Sam 07:00-14:00',
                'closes_at' => '19:00',
                'temporary_closed' => false,
                'emergency_available' => true,
                'services' => 'PCR, Serologie, Bacteriologie, Test de grossesse',
                'payment_methods' => 'Cash (HTG/USD), MonCash, Sogebank, Unibank',
                'price_range' => 'high',
                'average_wait_time' => 30,
                'delivery_available' => true,
                'delivery_radius_km' => 8.5,
                'night_service' => false,
                'license_number' => 'LAB-PAP-2002',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Prelevements a domicile sur rendez-vous.',
            ],
            [
                'name' => 'Laboratoire MedCheck Champs de Mars',
                'phone' => '+509-2811-4103',
                'address' => 'Avenue Magloire Ambroise, Port-au-Prince',
                'latitude' => 18.5398,
                'longitude' => -72.3368,
                'open_now' => false,
                'opening_hours' => 'Lun-Ven 07:30-17:30; Sam 08:00-13:00',
                'closes_at' => '17:30',
                'temporary_closed' => false,
                'emergency_available' => false,
                'services' => 'Fonction renale, Fonction hepatique, Electrolytes, Groupage sanguin',
                'payment_methods' => 'Cash (HTG), MonCash, NatCash',
                'price_range' => 'medium',
                'average_wait_time' => 25,
                'delivery_available' => false,
                'delivery_radius_km' => null,
                'night_service' => false,
                'license_number' => 'LAB-PAP-2003',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Jeune recommande pour certains examens sanguins.',
            ],
            [
                'name' => 'LabExpress Petion-Ville',
                'phone' => '+509-2811-4104',
                'address' => 'Rue Clerveaux, Petion-Ville',
                'latitude' => 18.5137,
                'longitude' => -72.2894,
                'open_now' => true,
                'opening_hours' => 'Lun-Sam 06:00-20:00; Dim 08:00-12:00',
                'closes_at' => '20:00',
                'temporary_closed' => false,
                'emergency_available' => true,
                'services' => 'Tests rapides, Toxicologie, Thyroide, Marqueurs cardiaques',
                'payment_methods' => 'Cash (HTG/USD), MonCash, Carte de debit locale',
                'price_range' => 'high',
                'average_wait_time' => 18,
                'delivery_available' => true,
                'delivery_radius_km' => 10.0,
                'night_service' => true,
                'license_number' => 'LAB-PAP-2004',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Service prioritaire pour analyses urgentes.',
            ],
            [
                'name' => 'Laboratoire Sante Plus Carrefour',
                'phone' => '+509-2811-4105',
                'address' => 'Carrefour, Zone Bizoton',
                'latitude' => 18.5416,
                'longitude' => -72.3992,
                'open_now' => true,
                'opening_hours' => 'Lun-Ven 07:00-18:30; Sam 07:00-13:30',
                'closes_at' => '18:30',
                'temporary_closed' => false,
                'emergency_available' => false,
                'services' => 'Parasitologie, Coproculture, Examen prenatal, Profil diabetique',
                'payment_methods' => 'Cash (HTG), MonCash, NatCash',
                'price_range' => 'low',
                'average_wait_time' => 22,
                'delivery_available' => false,
                'delivery_radius_km' => null,
                'night_service' => false,
                'license_number' => 'LAB-PAP-2005',
                'license_verified' => false,
                'account_verification_status' => 'pending',
                'logo_url' => null,
                'storefront_image_url' => null,
                'notes_for_patients' => 'Tarifs sociaux certains jours de la semaine.',
            ],
        ];

        foreach ($rows as $row) {
            Laboratory::updateOrCreate(
                ['name' => $row['name']],
                array_merge($row, [
                    'license_verified_at' => null,
                    'license_verified_by_doctor_id' => null,
                    'license_verification_notes' => null,
                    'last_status_updated_at' => now(),
                ])
            );
        }
    }
}

